
name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

env:
  SOLUTION_NAME: src\CTrue.FsConnect.sln

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v2
      
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.3
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      
      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_NAME }}

      - name: Build
        run: msbuild ${{ env.SOLUTION_NAME }} /p:Configuration=Release
